flags:
  android:
    paths:
      - android/
    carryforward: true
  stats-server:
    paths:
      - stats-server/
    carryforward: true
  client:
    paths:
      - client/
    carryforward: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
      android:
        target: auto
        threshold: 1%
        flags:
          - android
      stats-server:
        target: auto
        threshold: 1%
        flags:
          - stats-server
      client:
        target: auto
        threshold: 1%
        flags:
          - client
    patch:
      default:
        target: 80%
        threshold: 1%
